package jfuzz.engines.messages;

import jfuzz.engines.EngineName;

/**
 * The Exit message is a signal that the system should shut down.
 * 
 * Generated by Any Engine.
 * Consumed by Every Engine.
 */
public class ExitMessage extends Message {

	public ExitMessage(EngineName source) {
		super(source,QueueName.ExitMessage);
	}

	@Override
	public void handleAccept(MessageHandler handler) {
		handler.handleMessage(this);
	}

	@Override
	public String toString() {
		return "Message: [Pipeline: Exit] " + sequence;
	}

	@Override
	public int bytes() {
		return 1;
	}
	
}
